import { resolve } from "node:path";
import { writeFile } from "node:fs/promises";
import { Registry } from "@/types";

export class BarrelService {
  constructor(private outDir: string) {}

  async sync(registry: Registry): Promise<void> {
    const indexPath = resolve(process.cwd(), this.outDir, "index.ts");

    const imports = Object.values(registry)
      .sort((a, b) => a.componentName.localeCompare(b.componentName))
      .map(
        (meta) => `import { ${meta.componentName} } from "./${meta.fileName}";`
      );

    const contantsExports = Object.values(registry)
      .sort((a, b) => a.componentName.localeCompare(b.componentName))
      .map((meta) => `  ${meta.componentName},`);

    const content = [
      "// Auto-generated by IconCraft",
      "// Do not edit this file directly",
      "",
      ...imports,
      "",
      "export const Icon = {",
      ...contantsExports,
      "}",
      "",
    ].join("\n");

    await writeFile(indexPath, content, "utf8");
  }
}
