import { resolve } from "node:path";
import { writeFile } from "node:fs/promises";
import { Registry } from "@/types";

export class BarrelService {
  constructor(private outDir: string) {}

  async sync(registry: Registry): Promise<void> {
    const indexPath = resolve(process.cwd(), this.outDir, "index.ts");

    const exports = Object.values(registry)
      .sort((a, b) => a.componentName.localeCompare(b.componentName))
      .map(
        (meta) =>
          `export { default as ${meta.componentName} } from "./${meta.fileName}";`
      );

    const content = [
      "// Auto-generated by IconCraft",
      "// Do not edit this file directly",
      "",
      ...exports,
      "",
    ].join("\n");

    await writeFile(indexPath, content, "utf8");
  }
}
