export const HEALTH_ERROR_CODES = {
  CHECK_THROWN: "CHECK_THROWN",
  CHECK_TIMEOUT: "CHECK_TIMEOUT",
  CHECK_ABORTED: "CHECK_ABORTED",
  HEALTHCHECK_TIMEOUT: "HEALTHCHECK_TIMEOUT",
  HEALTHCHECK_ABORTED: "HEALTHCHECK_ABORTED",
  HEALTHCHECK_DEPENDENCY_UNAVAILABLE: "HEALTHCHECK_DEPENDENCY_UNAVAILABLE",
  HEALTHCHECK_CONTAINER_LIMIT_UNAVAILABLE: "HEALTHCHECK_CONTAINER_LIMIT_UNAVAILABLE",
  HEALTHCHECK_ROUTE_UNAUTHORIZED: "HEALTHCHECK_ROUTE_UNAUTHORIZED",
  HEALTHCHECK_INVALID_CONFIG: "HEALTHCHECK_INVALID_CONFIG",
  HTTP_STATUS_MISMATCH: "HTTP_STATUS_MISMATCH",
  HTTP_BODY_MISMATCH: "HTTP_BODY_MISMATCH",
  TCP_CONNECT_FAILED: "TCP_CONNECT_FAILED",
  DNS_RESOLVE_FAILED: "DNS_RESOLVE_FAILED",
  DATABASE_PING_FAILED: "DATABASE_PING_FAILED",
  PAYLOAD_QUERY_FAILED: "PAYLOAD_QUERY_FAILED",
  RUNTIME_UNSUPPORTED: "RUNTIME_UNSUPPORTED",
  METRIC_UNAVAILABLE: "METRIC_UNAVAILABLE",
} as const;

export type HealthErrorCode
  = (typeof HEALTH_ERROR_CODES)[keyof typeof HEALTH_ERROR_CODES];
